# Copyright 2017 The Gardener Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: vpn-shoot
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-shoot
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
      labels:
        app: vpn-shoot
    spec:
      tolerations:
      - effect: NoExecute
        operator: Exists
      containers:
      - name: vpn-shoot
        image: eu.gcr.io/sap-cloud-platform-dev1/garden/vpn/shoot:v0.0.7
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        resources:
          requests:
            cpu: 100m
        volumeMounts:
        - name: vpn-ssh-authorized-keys
          mountPath: /root/.ssh
        - name: vpn-sshd-config
          mountPath: /etc/ssh/sshd_config
          subPath: sshd_config
      volumes:
      - name: vpn-ssh-authorized-keys
        secret:
          secretName: vpn-ssh-authorized-keys
      - name: vpn-sshd-config
        configMap:
          name: vpn-sshd-config
